import assert from "node:assert/strict";
const base = process.env.TEST_BASE_URL || "http://localhost:3000";
// Local preview only: Sites itself supplies these headers in production.
assert.ok(new URL(base).hostname === "localhost" || new URL(base).hostname === "127.0.0.1");
const admin = { "oai-authenticated-user-id": "local-admin-test", "oai-authenticated-user-email": "Info@remarcableliving.co" };
const outsider = { ...admin, "oai-authenticated-user-email": "not-an-admin@example.com" };
assert.equal((await fetch(`${base}/api/media`)).status, 403);
assert.equal((await fetch(`${base}/api/media`, { headers: outsider })).status, 403);
assert.equal((await fetch(`${base}/api/listings?admin=1`, { headers: outsider })).status, 401);
assert.equal((await fetch(`${base}/api/media`, { method: "POST", headers: { ...admin, origin: "https://other.example", "content-type": "image/png" }, body: "test" })).status, 403);
assert.equal((await fetch(`${base}/api/media`, { method: "POST", headers: { ...admin, origin: base, "content-type": "image/svg+xml" }, body: "<svg/>" })).status, 415);
const bytes = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII=", "base64");
const response = await fetch(`${base}/api/media`, { method: "POST", headers: { ...admin, origin: base, "content-type": "image/png", "x-file-name": "local-test.png" }, body: bytes });
const uploaded = await response.json();
assert.equal(response.status, 201, JSON.stringify(uploaded));
const retrieved = await fetch(base + uploaded.item.url);
assert.equal(retrieved.status, 200);
assert.equal(retrieved.headers.get("content-type"), "image/png");
assert.deepEqual(Buffer.from(await retrieved.arrayBuffer()), bytes);
const partial = await fetch(base + uploaded.item.url, { headers: { range: "bytes=0-7" } });
assert.equal(partial.status, 206);
assert.equal(partial.headers.get("content-range"), `bytes 0-7/${bytes.length}`);
assert.deepEqual(Buffer.from(await partial.arrayBuffer()), bytes.subarray(0, 8));
const suffix = await fetch(base + uploaded.item.url, { headers: { range: "bytes=-8" } });
assert.equal(suffix.status, 206);
assert.deepEqual(Buffer.from(await suffix.arrayBuffer()), bytes.subarray(-8));
const invalidRange = await fetch(base + uploaded.item.url, { headers: { range: "bytes=999999-" } });
assert.equal(invalidRange.status, 416);
const library = await (await fetch(`${base}/api/media`, { headers: admin })).json();
assert.ok(library.items.some(item => item.url === uploaded.item.url && item.name === "local-test.png" && item.type === "image/png"));
assert.match(await (await fetch(`${base}/admin`, { headers: admin })).text(), /Images &amp; videos/);
console.log("Passed: admin restrictions, cross-origin rejection, file validation, streaming upload, retrieval, range playback, library metadata, admin page.");
