#!/usr/bin/env python3
"""Generate a public, privacy-reduced inventory seed from the supplied CSV.

Only rows explicitly marked available are included. Internal access notes,
addresses, negotiability notes, remarks, sheet names, raw unit numbers, and
unit codes are deliberately excluded from the public artifact.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
from pathlib import Path
from urllib.parse import urlsplit


def clean(value: str | None) -> str:
    return " ".join((value or "").strip().split())


def parse_price(value: str) -> int | None:
    match = re.search(r"(?<!\d)(\d{1,3}(?:,\d{3})+|\d{4,7})(?!\d)", value)
    if not match:
        return None
    price = int(match.group(1).replace(",", ""))
    return price if 5_000 <= price <= 1_000_000 else None


def parse_area(value: str) -> float | None:
    normalized = value.replace(",", "")
    if not re.fullmatch(r"\d+(?:\.\d+)?", normalized):
        return None
    area = float(normalized)
    return area if 10 <= area <= 1_000 else None


def public_direction(value: str) -> str | None:
    if not value or len(value) > 40:
        return None
    if not re.search(r"north|south|east|west|city|pool|garden|river|park|school|facility|mrt", value, re.I):
        return None
    return value


def public_photo_url(value: str) -> str | None:
    for candidate in re.split(r"\s+\|\s+", value):
        if not candidate or re.search(r"\s", candidate):
            continue
        try:
            parsed = urlsplit(candidate)
        except ValueError:
            continue
        if parsed.scheme == "https" and parsed.netloc:
            return candidate
    return None


def public_project(row: dict[str, str]) -> str:
    project = clean(row.get("Project"))
    unit = clean(row.get("Unit"))
    if project == "FULL COMMISSION FROM NOW UNTIL 31 May 2022!" and re.search(r"[A-Za-z]", unit):
        return unit
    return {
        "FULL COMMISSION FROM NOW UNTIL 31 May 2022!": "Special promotion inventory",
        "Mid-Year Promotion.": "Mid-year promotion inventory",
        "Special Unit.": "Special unit inventory",
        "Rental Agent Cloud x Plus Property": "Plus Property partner inventory",
    }.get(project, project)


def public_floor(value: str) -> str | None:
    return value if value and value.lower() != "floor" and len(value) <= 30 else None


def public_unit_type(value: str) -> str | None:
    if re.fullmatch(r"\d+B/\d+B", value, re.I):
        return value.upper()
    if re.fullmatch(r"studio|duplex|penthouse", value, re.I):
        return value.title()
    return None


def make_reference(row: dict[str, str], ordinal: int) -> str:
    identity = "|".join(
        clean(row.get(key))
        for key in ("Project", "Unit", "Floor", "Address", "Unit code", "Photo links")
    )
    digest = hashlib.sha256(f"{identity}|{ordinal}".encode()).hexdigest()[:10].upper()
    return f"RL-{digest}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input_csv", type=Path)
    parser.add_argument("output_ts", type=Path)
    args = parser.parse_args()

    with args.input_csv.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))

    records: list[dict[str, object]] = []
    seen: set[str] = set()
    for ordinal, row in enumerate(rows, start=1):
        if clean(row.get("Status")).lower() != "available":
            continue
        project = public_project(row)
        if not project:
            continue
        floor = public_floor(clean(row.get("Floor")))
        unit_type = public_unit_type(clean(row.get("Unit type")))
        area = parse_area(clean(row.get("Area sq.m")))
        direction = public_direction(clean(row.get("Direction")))
        price = parse_price(clean(row.get("Price/month")))
        photo_url = public_photo_url(clean(row.get("Photo links")))
        if not any((unit_type, area, price, photo_url)):
            continue
        record = {
            "ref": make_reference(row, ordinal),
            "project": project,
            "floor": floor,
            "unitType": unit_type,
            "areaSqm": area,
            "direction": direction,
            "priceMonthly": price,
            "photoUrl": photo_url,
            "status": "available",
            "importedAt": "2026-08-26",
        }
        source_key = json.dumps({key: clean(value) for key, value in row.items()}, sort_keys=True)
        if source_key in seen:
            continue
        seen.add(source_key)
        records.append(record)

    payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
    output = (
        "// Generated by scripts/generate-imported-inventory.py. Do not edit manually.\n"
        "export type ImportedInventoryUnit = {\n"
        "  ref: string; project: string; floor: string | null; unitType: string | null;\n"
        "  areaSqm: number | null; direction: string | null; priceMonthly: number | null;\n"
        "  photoUrl: string | null; status: \"available\"; importedAt: string;\n"
        "};\n\n"
        f"export const importedInventory: ImportedInventoryUnit[] = {payload};\n"
        f"export const importedInventoryCount = {len(records)};\n"
    )
    args.output_ts.parent.mkdir(parents=True, exist_ok=True)
    args.output_ts.write_text(output, encoding="utf-8")
    print(len(records))


if __name__ == "__main__":
    main()
